on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  amd64_build:
    name: Setup Output and Build for amd64
    runs-on: ubuntu-18.04
    container: robiot/xclicker
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build x64
        run: |
            mkdir -p outputs
            make deb TARGET_ARCH=amd64
            cp pkg/deb/*.deb ../outputs

      - uses: actions/upload-artifact@master
        with:
          name: output-artifact
          path: outputs
    
  build:
    name: Build for other Architechtures & Create Release
    runs-on: ubuntu-18.04
    needs: amd64_build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/download-artifact@master
        with:
          name: output-artifact
          path: outputs
    
      - name: Build ARM
        uses: uraimo/run-on-arch-action@v2.1.1
        with:
          arch: armv7
          distro: ubuntu18.04

          githubToken: ${{ github.token }}

          dockerRunArgs: |
            --volume "${PWD}/outputs:${PWD}/outputs"

          install: |
            apt-get update -y
            apt-get install -y meson pkg-config gtk+-3.0 libx11-dev libxi-dev libxtst-dev

          run: |
            make deb TARGET_ARCH=arm
            cp pkg/deb/*.deb ../outputs
    
      - name: Create Release
        uses: softprops/action-gh-release@v0.1.14
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          generate_release_notes: true
          draft: false
          prerelease: false
          files: |
            outputs/xclicker_${{ github.ref_name }}_amd64
            outputs/xclicker_${{ github.ref_name }}_arm
